# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'grpc-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for grpc-test
  pod 'gRPC-Swift'
end
